ClusterCockpit/cc-backend

cmd/cc-backend/main.go, internal/auth/auth.go, internal/auth/users.go, internal/graph/schema.resolvers.go, internal/repository/job.go, internal/repository/query.go, internal/routerConfig/routes.go, web/templates/config.tmpl, web/web.go
This pull request addresses issue #40. In daily user support, there are occasionally cases where it is helpful to be able to read the recorded metrics of a job. Until now, this was only possible if the supporter in question had admin rights. However, this would also allow him to read out authentication characteristics of another user. 
The new role "Support" gives a user the possibility to see all jobs without giving him admin rights.
=> Add new role support. This enables designated users to see all jobs.

cmd/cc-backend/main.go, pkg/archive/archive.go, test/integration_test.go
Hi,
I had an error while creating new jobs via the REST API.
```
Error while inserting job: open var/job-archive/levante/2546/857/1667913761/meta.json: no such file or directory
```
The issue seems to be updating of tags when the config 'disable-archive' is set to true.
I made the archive aware of the disabled status, allowing to insert jobs with 'completed' state and flags in combination with disabled archiving.
=> fix adding tag with disabled archive

internal/api/rest.go, internal/repository/job.go
For requeued jobs, we might have multiple jobs with matching cluster and job id, but differing start time. So check all of the matching ones against the start time.
This takes care of one issue that's related to #30.
=> Upon start job, compare start time against all matching jobs.

internal/api/rest.go, test/integration_test.go
Hi,
I would like to propose fixes for #68 and #46.
The race condition mentioned in #46 should be avoided by synchronizing the findall call to the job-repo.
The job state is no longer overwritten and just defaults to 'completed' if not given by the user.
Let me know what you think,
Cheers,
=> Preserve job state in stopJob and secure startJob by Mutex

cmd/cc-backend/main.go, internal/api/rest.go, internal/repository/job.go, test/integration_test.go
Hi,
I would like to propose a change to the job-archiving mechanism. So far the API is starting a worker thread for each stop_job request. 
We observed two potential issues with that: If you push jobs very fast, you can run either into open file limits of the OS (meta.json and data.json for each job) or even earlier run into max parallel connections of a metricdata database.
This might not apply to cc_metric_store, but for prometheus and influx databases.
I didn't change the order of operations, but job's are pushed into a channel and archived by a worker thread in the job repository.
From my understanding this also moves job-repo functionality out of the api code.
The API calls will block, once the channel (size 128) is full, which is a good rate limiting mechanism I think.
There's one …
=> archive jobs in single worker thread

web/frontend/src/joblist/JobInfo.svelte, web/frontend/src/joblist/JobList.svelte
We have a rather heterogeneous cluster, so it's quite interesting where a job ran.
Also, currently, all jobs are single node ones.
Therefore, for us it's quite useful to have the hostname shown as part of the JobInfo in the list and the job view, as well as the subcluster, which is helpful to understand which hardware configuration the node had.
This e.g. looks like this:
I'm not sure how generally useful this is, but I still wanted to post the patch :)
=> Add node name and sub-cluster to JobInfo.

configs/README.md, configs/config.json, internal/config/config.go, internal/repository/job.go, internal/repository/user.go, internal/routerConfig/routes.go, pkg/schema/config.go, pkg/schema/schemas/config.schema.json
Setting was already present as user-based `plot_list_hideShortRunningJobs` setting, but also hardcoded for other queries.
Moved to root application config as `ShortRunningJobsDuration`, will be injected into user-based UI-config for frontend use.
=> Move ShortRunningJobsDuration value to root config

api/schema.graphqls, internal/graph/generated/generated.go, internal/graph/model/models_gen.go, internal/graph/schema.resolvers.go, internal/repository/job.go, web/frontend/src/Analysis.root.svelte, web/frontend/src/Jobs.root.svelte, web/frontend/src/List.root.svelte, web/frontend/src/User.root.svelte, web/frontend/src/joblist/JobList.svelte
Fatal crash in cc-backend verly likely caused by parallel access of metaData cache during handling of metaData and jobName fields.
The latter was unused and is non-required, as every handling of jobNames is done by accessingthem via metaData object in frontend, oh handling metaData as a whole in backend (e.g. jobName searchbar query)
Additional changes:
* Correct implementation of filter-/component (-functions) in svelte frontend
* Switch `name` field in gql scheme for JobStatistics to required, returns string
=> 121 fix filter reactivity crash

tools/archive-migration/main.go
We discovered one data.json file with a size of 0 Bytes. Empty data sets do not need a migration, so we can skip them.
=> Skip files with size of 0 Bytes

cmd/cc-backend/main.go, internal/api/rest.go, internal/auth/auth.go, internal/repository/hooks.go, internal/repository/job.go, internal/repository/query.go, internal/repository/stats.go, web/web.go
Hi,
I would like to propose lower log-levels for timers and some of the very frequent log messages, I think they belong into debug and quickly fill a log if you run a production instance on 'info' level.
Cheers,
Pay
=> lower log level for frequent messages

internal/metricdata/prometheus.go
Hi,
I would like to merge a fix in the prometheus backend. In case of missing data from all hosts of some metric, the backend would so far return a jobMetric object with a Series of length zero. This causes the frontend to crash inside MetricPlot.svelte where some checks rely on series[0].data.length
This PR only adds scope/metric data if at least one host returned values and fixes the issue.
=> Prometheus backend: omit metrics with empty series

web/frontend/src/Job.root.svelte, web/frontend/src/StatsTable.svelte, web/frontend/src/StatsTableEntry.svelte
Stats Table in Job View loads granular metrics if
* Job not Exclusive or not single node job -> Get maxScope() automatic
* No Accelerators in Job *and* not Acc-Metric -> Use 'core' (== hwtread) by default
* Accelerator Metric available with config'd accelerator scope -> Use 'accelerator' by default
* Accelerator Metric only on node scope -> Fallback and use 'node'
=> 138 show core accelerator scope statstable

configs/README.md, internal/auth/ldap.go, internal/repository/user.go, pkg/schema/config.go, pkg/schema/schemas/config.schema.json
Hi,
I would like to propose a small improvement to the ldap auth module: In our LDAP, full user names are stored in the 'cn' attribute, not in 'gecos'.
I made the attribute to look for user names a config option which defaults to 'gecos' if not provided. Shouldn't break with older configs like this.
Also fixes a small bug in DelUser where the error log was printed independent of the error.
=> Ldap name config

web/frontend/src/Job.root.svelte
Quick fix via null-safe ternary operator
=> fix: fix crashing job view if roofline metrics missing

internal/api/rest.go, internal/repository/job.go, internal/repository/user.go, internal/routerConfig/routes.go
Prevents undead jobs if db job count is high and thus jobIds are overflowing/looping
=> Hotfix: add orderBy param to jobRepo.Find

internal/taskManager/updateFootprintService.go
* Remove non-required requested scopes 
* Use `repo.LoadStats` instead of `repo.LoadData`
* Decouple Transaction Init and Commits from Data-Loadduring statement preparation
Local Speedup, tested with Prod Data: from ~3:20m to ~9s
=> Improve footprint transactions

pkg/schema/config.go, pkg/schema/schemas/config.schema.json
=> Move to open Release PR

pkg/resampler/resampler.go
Resampler didnt handle when new resolution was lesser than native/old resolution.
Now resampler just returns old data with old resolution if ne resolution is finer/lesser than the old resolution.
=> fix: Update to resampler handling different resolutions

go.mod
If the local go version is not up to date, go was previously unable to obtain a more recent version, since the required version in go.mod is not available.
=> fix: Fix go version in go.mod

web/frontend/src/config/UserSettings.svelte, web/frontend/src/config/user/PlotColorScheme.svelte, web/frontend/src/config/user/PlotRenderOptions.svelte, web/frontend/src/generic/plots/MetricPlot.svelte, web/frontend/src/generic/plots/Roofline.svelte
* add colorblind-mode setting and friendly plot coloring palettes
- mode applies to plot data, plot background color, statsseries colors, roofline timescale
Closes #317
=> add colorblind setting

internal/auth/auth.go
Fixed an error where SessionMaxAge was only set when parsing failed (err != nil).
Now correctly applies values from the config.
=> Fix SessionMaxAge condition to correctly apply valid values

configs/default_metrics.json, internal/config/default_metrics.go, internal/repository/user.go
This PR introduces a new mechanism to set default job-view metrics for all new users (both locally created and LDAP-imported). Instead of having every new user start with the full list of metrics—which can be overwhelming—we now load a smaller subset of default metrics from an external configuration file.
* A new JSON file is added at `configs/default_metrics.json` where you can define default metrics for each cluster. 
* During user creation (using the existing AddUser function), the system checks for the presence of the `configs/default_metrics.json` file. For every cluster defined in the file, a new configuration entry is inserted into the database under the key `job_view_selectedMetrics:<cluster name>` with the metrics parsed by splitting the comma-separated string. The order …
=> Add config for default of job_view_selectedMetrics:<cluster_name>

internal/metricDataDispatcher/dataLoader.go, pkg/schema/metrics.go
See #329 
* Adds centralized && cached rounding in `dataLoader.go` before data is sent to subsequent components.
* Allows metric-interface developers to return raw values.
=> Add stats rounding data loader

web/frontend/src/systems/nodelist/NodeListRow.svelte
- allows for more information on all exclusivity states, instead of missing information if exclusivity job flag is always exclusive
- changed from "use for shared nodes only"
=> use extendedLegend in nodeList for all non-idle nodes

ReleaseNotes.md, internal/graph/schema.resolvers.go, web/frontend/src/Job.root.svelte
If backend-default `UiDefaults["job_list_usePaging"]` was set to `true`, the `hasNextPage`-Boolean was never returned to the frontend.
It was still possible for frontend users to activate continuous scrolling, and if they did, this resulted in unresponsive job lists, i.e. no data would be added apart from the first ten jobs.
Remove dependency on `uiDefaults` setting for `jobs` GQL Endpoint
=> fix: always return hasNextPage boolean to frontend

internal/auth/auth.go
This PR fixes a small mistake in the `AuthApi` function (file: `internal/auth/auth.go`).
Currently, when `securedCheck` returns an error (`ipErr`), the following line tries to log the error:
```
log.Infof("auth api -> secured check failed: %s", err.Error())
```
However, the variable `err` does not exist at this point — it should be `ipErr`.  
This leads to a panic at runtime if an authorization error occurs:
```
runtime error: invalid memory address or nil pointer dereference
goroutine 4889 [running]:
runtime/debug.Stack()
github.com/gorilla/handlers.recoveryHandler.log
github.com/gorilla/handlers.recoveryHandler.ServeHTTP.func1
panic()
main.serverInit.func9.(*Authentication).AuthApi
...
```
=> [BUGFIX] correct wrong variable in AuthApi error logging
